/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/platform/platform';
import * as import10 from '../../providers/connection-service';
import * as import11 from 'ionic-angular/components/alert/alert';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from 'ionic-angular/components/toolbar/toolbar';
import * as import15 from 'ionic-angular/components/navbar/navbar';
import * as import16 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/components/button/button';
import * as import19 from 'ionic-angular/components/icon/icon';
import * as import20 from 'ionic-angular/components/content/content';
import * as import21 from 'ionic-angular/components/grid/grid';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import26 from 'ionic-angular/components/app/app';
import * as import27 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomePage_0_4:import3.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import3.HomePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Platform),this.parentInjector.get(import10.ConnectionService),this.parentInjector.get(import11.AlertController));
    this._appEl_0.initComponent(this._HomePage_0_4,([] as any[]),compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import13.ComponentFactory<import3.HomePage> = new import13.ComponentFactory<import3.HomePage>('page-home',viewFactory_HomePage_Host0,import3.HomePage);
const styles_HomePage:any[] = ([] as any[]);
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import3.HomePage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import14.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import15.Navbar;
  _text_4:any;
  _el_5:any;
  _ToolbarItem_5_3:import16.ToolbarItem;
  _query_Button_5_0:import17.QueryList<any>;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _Button_7_4:import18.Button;
  _text_8:any;
  _el_9:any;
  _Icon_9_3:import19.Icon;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _Content_15_4:import20.Content;
  _text_16:any;
  _el_17:any;
  _Grid_17_3:import21.Grid;
  _text_18:any;
  _el_19:any;
  _Row_19_3:import21.Row;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _Row_33_3:import21.Row;
  _text_34:any;
  _el_35:any;
  _Grid_35_3:import21.Grid;
  _text_36:any;
  _el_37:any;
  _Row_37_3:import21.Row;
  _text_38:any;
  _el_39:any;
  _Col_39_3:import21.Col;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _Button_41_4:import18.Button;
  _text_42:any;
  _el_43:any;
  _Grid_43_3:import21.Grid;
  _text_44:any;
  _el_45:any;
  _Row_45_3:import21.Row;
  _text_46:any;
  _el_47:any;
  _Icon_47_3:import19.Icon;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _Row_50_3:import21.Row;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _Col_59_3:import21.Col;
  _text_60:any;
  _el_61:any;
  /*private*/ _appEl_61:import2.AppElement;
  _Button_61_4:import18.Button;
  _text_62:any;
  _el_63:any;
  _Grid_63_3:import21.Grid;
  _text_64:any;
  _el_65:any;
  _Row_65_3:import21.Row;
  _text_66:any;
  _el_67:any;
  _Icon_67_3:import19.Icon;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _Row_70_3:import21.Row;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _Row_80_3:import21.Row;
  _text_81:any;
  _el_82:any;
  _Col_82_3:import21.Col;
  _text_83:any;
  _el_84:any;
  /*private*/ _appEl_84:import2.AppElement;
  _Button_84_4:import18.Button;
  _text_85:any;
  _el_86:any;
  _Grid_86_3:import21.Grid;
  _text_87:any;
  _el_88:any;
  _Row_88_3:import21.Row;
  _text_89:any;
  _el_90:any;
  _Icon_90_3:import19.Icon;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  _Row_93_3:import21.Row;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _el_102:any;
  _Col_102_3:import21.Col;
  _text_103:any;
  _el_104:any;
  /*private*/ _appEl_104:import2.AppElement;
  _Button_104_4:import18.Button;
  _text_105:any;
  _el_106:any;
  _Grid_106_3:import21.Grid;
  _text_107:any;
  _el_108:any;
  _Row_108_3:import21.Row;
  _text_109:any;
  _el_110:any;
  _Icon_110_3:import19.Icon;
  _text_111:any;
  _text_112:any;
  _el_113:any;
  _Row_113_3:import21.Row;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _text_117:any;
  _text_118:any;
  _text_119:any;
  _text_120:any;
  _text_121:any;
  _text_122:any;
  _text_123:any;
  _text_124:any;
  _text_125:any;
  _text_126:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import14.Header(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import24.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','hometab');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import25.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import15.Navbar(this.parentInjector.get(import26.App),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_5,'end','');
    this._ToolbarItem_5_3 = new import16.ToolbarItem(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import14.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_5_0 = new import17.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'clear','');
    this.renderer.setElementAttribute(this._el_7,'ion-button','');
    this._appEl_7 = new import2.AppElement(7,5,this,this._el_7);
    var compView_7:any = import27.viewFactory_Button0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Button_7_4 = new import18.Button((null as any),'',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_7),this.renderer);
    this._appEl_7.initComponent(this._Button_7_4,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_9,'name','settings');
    this.renderer.setElementAttribute(this._el_9,'role','img');
    this._Icon_9_3 = new import19.Icon(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_7.create(this._Button_7_4,[([] as any[]).concat([
        this._text_8,
        this._el_9,
        this._text_10
      ]
    )],(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_5]),
      ([] as any[]).concat([
        this._text_4,
        this._text_12
      ]
      )
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_15 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','home home-background');
    this.renderer.setElementAttribute(this._el_15,'padding-5','');
    this._appEl_15 = new import2.AppElement(15,(null as any),this,this._el_15);
    var compView_15:any = import28.viewFactory_Content0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Content_15_4 = new import20.Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import26.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_15.initComponent(this._Content_15_4,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_17_3 = new import21.Grid();
    this._text_18 = this.renderer.createText(this._el_17,'\n',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','homerow');
    this._Row_19_3 = new import21.Row();
    this._text_20 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','center');
    this._text_22 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'img',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','pt-page-moveFromTopFade sslogo');
    this.renderer.setElementAttribute(this._el_23,'src','assets/images/sslogo.svg');
    this._text_24 = this.renderer.createText(this._el_21,'\n      \n      ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_21,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','pt-page-moveFromTopFade');
    this._text_26 = this.renderer.createText(this._el_25,'DARTH',(null as any));
    this._text_27 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_21,'h6',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','pt-page-moveFromTopFade');
    this._text_29 = this.renderer.createText(this._el_28,'Complete Retail Solution',(null as any));
    this._text_30 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_19,'\n',(null as any));
    this._text_32 = this.renderer.createText(this._el_17,'\n',(null as any));
    this._el_33 = this.renderer.createElement(this._el_17,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','homerow');
    this._Row_33_3 = new import21.Row();
    this._text_34 = this.renderer.createText(this._el_33,'\n  ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'ion-grid',(null as any));
    this._Grid_35_3 = new import21.Grid();
    this._text_36 = this.renderer.createText(this._el_35,'\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'ion-row',(null as any));
    this._Row_37_3 = new import21.Row();
    this._text_38 = this.renderer.createText(this._el_37,'\n      ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','center-icon pt-page-fade');
    this.renderer.setElementAttribute(this._el_39,'width-50','');
    this._Col_39_3 = new import21.Col();
    this._text_40 = this.renderer.createText(this._el_39,'\n          ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'button',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','home-button pt-page-moveFromLeftFade');
    this.renderer.setElementAttribute(this._el_41,'clear','');
    this.renderer.setElementAttribute(this._el_41,'ion-button','');
    this._appEl_41 = new import2.AppElement(41,39,this,this._el_41);
    var compView_41:any = import27.viewFactory_Button0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Button_41_4 = new import18.Button((null as any),'',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_41),this.renderer);
    this._appEl_41.initComponent(this._Button_41_4,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_43_3 = new import21.Grid();
    this._text_44 = this.renderer.createText(this._el_43,'\n              ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'ion-row',(null as any));
    this._Row_45_3 = new import21.Row();
    this._text_46 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','center-icon ionfontstyle');
    this.renderer.setElementAttribute(this._el_47,'name','trending-up');
    this.renderer.setElementAttribute(this._el_47,'role','img');
    this._Icon_47_3 = new import19.Icon(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_47),this.renderer);
    this._text_48 = this.renderer.createText(this._el_45,'\n              ',(null as any));
    this._text_49 = this.renderer.createText(this._el_43,'\n              ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_43,'ion-row',(null as any));
    this._Row_50_3 = new import21.Row();
    this._text_51 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_50,'span',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','center-icon ');
    this._text_53 = this.renderer.createText(this._el_52,'SALES',(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n              ',(null as any));
    this._text_55 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n          ',(null as any));
      compView_41.create(this._Button_41_4,[([] as any[]).concat([
        this._text_42,
        this._el_43,
        this._text_56
      ]
    )],(null as any));
    this._text_57 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._text_58 = this.renderer.createText(this._el_37,'\n      ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_37,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','center pt-page-fade');
    this.renderer.setElementAttribute(this._el_59,'width-50','');
    this._Col_59_3 = new import21.Col();
    this._text_60 = this.renderer.createText(this._el_59,'\n          ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'button',(null as any));
    this.renderer.setElementAttribute(this._el_61,'class','home-button  pt-page-moveFromRightFade');
    this.renderer.setElementAttribute(this._el_61,'clear','');
    this.renderer.setElementAttribute(this._el_61,'ion-button','');
    this._appEl_61 = new import2.AppElement(61,59,this,this._el_61);
    var compView_61:any = import27.viewFactory_Button0(this.viewUtils,this.injector(61),this._appEl_61);
    this._Button_61_4 = new import18.Button((null as any),'',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_61),this.renderer);
    this._appEl_61.initComponent(this._Button_61_4,([] as any[]),compView_61);
    this._text_62 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_63 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_63_3 = new import21.Grid();
    this._text_64 = this.renderer.createText(this._el_63,'\n              ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_63,'ion-row',(null as any));
    this._Row_65_3 = new import21.Row();
    this._text_66 = this.renderer.createText(this._el_65,'\n                ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_65,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','center-icon ionfontstyle');
    this.renderer.setElementAttribute(this._el_67,'name','basket');
    this.renderer.setElementAttribute(this._el_67,'role','img');
    this._Icon_67_3 = new import19.Icon(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_67),this.renderer);
    this._text_68 = this.renderer.createText(this._el_65,'\n              ',(null as any));
    this._text_69 = this.renderer.createText(this._el_63,'\n              ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_63,'ion-row',(null as any));
    this._Row_70_3 = new import21.Row();
    this._text_71 = this.renderer.createText(this._el_70,'\n                ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_70,'span',(null as any));
    this.renderer.setElementAttribute(this._el_72,'class','center-icon');
    this._text_73 = this.renderer.createText(this._el_72,'STOCKS',(null as any));
    this._text_74 = this.renderer.createText(this._el_70,'\n              ',(null as any));
    this._text_75 = this.renderer.createText(this._el_63,'\n            ',(null as any));
    this._text_76 = this.renderer.createText((null as any),'\n          ',(null as any));
      compView_61.create(this._Button_61_4,[([] as any[]).concat([
        this._text_62,
        this._el_63,
        this._text_76
      ]
    )],(null as any));
    this._text_77 = this.renderer.createText(this._el_59,'\n      ',(null as any));
    this._text_78 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._text_79 = this.renderer.createText(this._el_35,'\n    ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_35,'ion-row',(null as any));
    this._Row_80_3 = new import21.Row();
    this._text_81 = this.renderer.createText(this._el_80,'\n      ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','center pt-page-fade');
    this.renderer.setElementAttribute(this._el_82,'width-50','');
    this._Col_82_3 = new import21.Col();
    this._text_83 = this.renderer.createText(this._el_82,'\n          ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_82,'button',(null as any));
    this.renderer.setElementAttribute(this._el_84,'class','home-button pt-page-moveFromLeftFade');
    this.renderer.setElementAttribute(this._el_84,'clear','');
    this.renderer.setElementAttribute(this._el_84,'ion-button','');
    this._appEl_84 = new import2.AppElement(84,82,this,this._el_84);
    var compView_84:any = import27.viewFactory_Button0(this.viewUtils,this.injector(84),this._appEl_84);
    this._Button_84_4 = new import18.Button((null as any),'',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_84),this.renderer);
    this._appEl_84.initComponent(this._Button_84_4,([] as any[]),compView_84);
    this._text_85 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_86 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_86_3 = new import21.Grid();
    this._text_87 = this.renderer.createText(this._el_86,'\n              ',(null as any));
    this._el_88 = this.renderer.createElement(this._el_86,'ion-row',(null as any));
    this._Row_88_3 = new import21.Row();
    this._text_89 = this.renderer.createText(this._el_88,'\n                ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_88,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_90,'class','center-icon ionfontstyle');
    this.renderer.setElementAttribute(this._el_90,'name','cart');
    this.renderer.setElementAttribute(this._el_90,'role','img');
    this._Icon_90_3 = new import19.Icon(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_90),this.renderer);
    this._text_91 = this.renderer.createText(this._el_88,'\n              ',(null as any));
    this._text_92 = this.renderer.createText(this._el_86,'\n              ',(null as any));
    this._el_93 = this.renderer.createElement(this._el_86,'ion-row',(null as any));
    this._Row_93_3 = new import21.Row();
    this._text_94 = this.renderer.createText(this._el_93,'\n                ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_93,'span',(null as any));
    this.renderer.setElementAttribute(this._el_95,'class','center-icon ');
    this._text_96 = this.renderer.createText(this._el_95,'PURCHASE',(null as any));
    this._text_97 = this.renderer.createText(this._el_93,'\n              ',(null as any));
    this._text_98 = this.renderer.createText(this._el_86,'\n            ',(null as any));
    this._text_99 = this.renderer.createText((null as any),'\n          ',(null as any));
      compView_84.create(this._Button_84_4,[([] as any[]).concat([
        this._text_85,
        this._el_86,
        this._text_99
      ]
    )],(null as any));
    this._text_100 = this.renderer.createText(this._el_82,'\n      ',(null as any));
    this._text_101 = this.renderer.createText(this._el_80,'\n      ',(null as any));
    this._el_102 = this.renderer.createElement(this._el_80,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_102,'class','center pt-page-fade');
    this.renderer.setElementAttribute(this._el_102,'width-50','');
    this._Col_102_3 = new import21.Col();
    this._text_103 = this.renderer.createText(this._el_102,'\n          ',(null as any));
    this._el_104 = this.renderer.createElement(this._el_102,'button',(null as any));
    this.renderer.setElementAttribute(this._el_104,'class','home-button  pt-page-moveFromRightFade');
    this.renderer.setElementAttribute(this._el_104,'clear','');
    this.renderer.setElementAttribute(this._el_104,'ion-button','');
    this._appEl_104 = new import2.AppElement(104,102,this,this._el_104);
    var compView_104:any = import27.viewFactory_Button0(this.viewUtils,this.injector(104),this._appEl_104);
    this._Button_104_4 = new import18.Button((null as any),'',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_104),this.renderer);
    this._appEl_104.initComponent(this._Button_104_4,([] as any[]),compView_104);
    this._text_105 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_106 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_106_3 = new import21.Grid();
    this._text_107 = this.renderer.createText(this._el_106,'\n              ',(null as any));
    this._el_108 = this.renderer.createElement(this._el_106,'ion-row',(null as any));
    this._Row_108_3 = new import21.Row();
    this._text_109 = this.renderer.createText(this._el_108,'\n                ',(null as any));
    this._el_110 = this.renderer.createElement(this._el_108,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_110,'class','center-icon ionfontstyle');
    this.renderer.setElementAttribute(this._el_110,'name','contacts');
    this.renderer.setElementAttribute(this._el_110,'role','img');
    this._Icon_110_3 = new import19.Icon(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_110),this.renderer);
    this._text_111 = this.renderer.createText(this._el_108,'\n              ',(null as any));
    this._text_112 = this.renderer.createText(this._el_106,'\n              ',(null as any));
    this._el_113 = this.renderer.createElement(this._el_106,'ion-row',(null as any));
    this._Row_113_3 = new import21.Row();
    this._text_114 = this.renderer.createText(this._el_113,'\n                ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_113,'span',(null as any));
    this.renderer.setElementAttribute(this._el_115,'class','center-icon ');
    this._text_116 = this.renderer.createText(this._el_115,'STAFF',(null as any));
    this._text_117 = this.renderer.createText(this._el_113,'\n              ',(null as any));
    this._text_118 = this.renderer.createText(this._el_106,'\n            ',(null as any));
    this._text_119 = this.renderer.createText((null as any),'\n          ',(null as any));
      compView_104.create(this._Button_104_4,[([] as any[]).concat([
        this._text_105,
        this._el_106,
        this._text_119
      ]
    )],(null as any));
    this._text_120 = this.renderer.createText(this._el_102,'\n      ',(null as any));
    this._text_121 = this.renderer.createText(this._el_80,'\n    ',(null as any));
    this._text_122 = this.renderer.createText(this._el_35,'\n    ',(null as any));
    this._text_123 = this.renderer.createText(this._el_33,'\n',(null as any));
    this._text_124 = this.renderer.createText(this._el_17,'\n',(null as any));
    this._text_125 = this.renderer.createText((null as any),'\n',(null as any));
    compView_15.create(this._Content_15_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_16,
        this._el_17,
        this._text_125
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_126 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_41,'click',this.eventHandler(this._handle_click_41_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_61,'click',this.eventHandler(this._handle_click_61_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_84,'click',this.eventHandler(this._handle_click_84_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_104,'click',this.eventHandler(this._handle_click_104_0.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._text_118,
      this._text_119,
      this._text_120,
      this._text_121,
      this._text_122,
      this._text_123,
      this._text_124,
      this._text_125,
      this._text_126
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.Icon) && (9 === requestNodeIndex))) { return this._Icon_9_3; }
    if (((token === import18.Button) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Button_7_4; }
    if (((token === import16.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarItem_5_3; }
    if (((token === import15.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Navbar_3_4; }
    if (((token === import14.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Header_1_3; }
    if (((token === import21.Row) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Row_19_3; }
    if (((token === import19.Icon) && (47 === requestNodeIndex))) { return this._Icon_47_3; }
    if (((token === import21.Row) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Row_45_3; }
    if (((token === import21.Row) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Row_50_3; }
    if (((token === import21.Grid) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Grid_43_3; }
    if (((token === import18.Button) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Button_41_4; }
    if (((token === import21.Col) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Col_39_3; }
    if (((token === import19.Icon) && (67 === requestNodeIndex))) { return this._Icon_67_3; }
    if (((token === import21.Row) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Row_65_3; }
    if (((token === import21.Row) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._Row_70_3; }
    if (((token === import21.Grid) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Grid_63_3; }
    if (((token === import18.Button) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._Button_61_4; }
    if (((token === import21.Col) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._Col_59_3; }
    if (((token === import21.Row) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._Row_37_3; }
    if (((token === import19.Icon) && (90 === requestNodeIndex))) { return this._Icon_90_3; }
    if (((token === import21.Row) && ((88 <= requestNodeIndex) && (requestNodeIndex <= 91)))) { return this._Row_88_3; }
    if (((token === import21.Row) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 97)))) { return this._Row_93_3; }
    if (((token === import21.Grid) && ((86 <= requestNodeIndex) && (requestNodeIndex <= 98)))) { return this._Grid_86_3; }
    if (((token === import18.Button) && ((84 <= requestNodeIndex) && (requestNodeIndex <= 99)))) { return this._Button_84_4; }
    if (((token === import21.Col) && ((82 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._Col_82_3; }
    if (((token === import19.Icon) && (110 === requestNodeIndex))) { return this._Icon_110_3; }
    if (((token === import21.Row) && ((108 <= requestNodeIndex) && (requestNodeIndex <= 111)))) { return this._Row_108_3; }
    if (((token === import21.Row) && ((113 <= requestNodeIndex) && (requestNodeIndex <= 117)))) { return this._Row_113_3; }
    if (((token === import21.Grid) && ((106 <= requestNodeIndex) && (requestNodeIndex <= 118)))) { return this._Grid_106_3; }
    if (((token === import18.Button) && ((104 <= requestNodeIndex) && (requestNodeIndex <= 119)))) { return this._Button_104_4; }
    if (((token === import21.Col) && ((102 <= requestNodeIndex) && (requestNodeIndex <= 120)))) { return this._Col_102_3; }
    if (((token === import21.Row) && ((80 <= requestNodeIndex) && (requestNodeIndex <= 121)))) { return this._Row_80_3; }
    if (((token === import21.Grid) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 122)))) { return this._Grid_35_3; }
    if (((token === import21.Row) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 123)))) { return this._Row_33_3; }
    if (((token === import21.Grid) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 124)))) { return this._Grid_17_3; }
    if (((token === import20.Content) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 125)))) { return this._Content_15_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const currVal_0:any = 'hometab';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_3_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    changed = false;
    const currVal_4:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Button_7_4.clear = currVal_4;
      changed = true;
      this._expr_4 = currVal_4;
    }
    if (changed) { this._appEl_7.componentView.markAsCheckOnce(); }
    const currVal_5:any = 'settings';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_9_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_15_4.ngOnInit(); }
    changed = false;
    const currVal_9:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Button_41_4.clear = currVal_9;
      changed = true;
      this._expr_9 = currVal_9;
    }
    if (changed) { this._appEl_41.componentView.markAsCheckOnce(); }
    const currVal_10:any = 'trending-up';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_47_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    changed = false;
    const currVal_13:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Button_61_4.clear = currVal_13;
      changed = true;
      this._expr_13 = currVal_13;
    }
    if (changed) { this._appEl_61.componentView.markAsCheckOnce(); }
    const currVal_14:any = 'basket';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Icon_67_3.name = currVal_14;
      this._expr_14 = currVal_14;
    }
    changed = false;
    const currVal_17:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._Button_84_4.clear = currVal_17;
      changed = true;
      this._expr_17 = currVal_17;
    }
    if (changed) { this._appEl_84.componentView.markAsCheckOnce(); }
    const currVal_18:any = 'cart';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._Icon_90_3.name = currVal_18;
      this._expr_18 = currVal_18;
    }
    changed = false;
    const currVal_21:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._Button_104_4.clear = currVal_21;
      changed = true;
      this._expr_21 = currVal_21;
    }
    if (changed) { this._appEl_104.componentView.markAsCheckOnce(); }
    const currVal_22:any = 'contacts';
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._Icon_110_3.name = currVal_22;
      this._expr_22 = currVal_22;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_7_4]);
        this._ToolbarItem_5_3._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_7_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_41_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_61_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_84_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_104_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._Icon_9_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_9,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_15_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_15,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_11:any = this._Icon_47_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_47,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_15:any = this._Icon_67_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_67,'hide',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_19:any = this._Icon_90_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_90,'hide',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_23:any = this._Icon_110_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_110,'hide',currVal_23);
      this._expr_23 = currVal_23;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_9_3.ngOnDestroy();
    this._Icon_47_3.ngOnDestroy();
    this._Icon_67_3.ngOnDestroy();
    this._Icon_90_3.ngOnDestroy();
    this._Icon_110_3.ngOnDestroy();
    this._Content_15_4.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToSetting()) !== false);
    return (true && pd_0);
  }
  private _handle_click_41_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToSale()) !== false);
    return (true && pd_0);
  }
  private _handle_click_61_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToStock()) !== false);
    return (true && pd_0);
  }
  private _handle_click_84_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToPurchase()) !== false);
    return (true && pd_0);
  }
  private _handle_click_104_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToStaff()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}